#!/bin/sh

set -e

case $KLC_NETWORK in
  local|regtest)
    SELECT_NETWORK=-regtest
    ;;
  test|testnet)
    SELECT_NETWORK=-testnet
    ;;
  main|mainnet)
    SELECT_NETWORK=
    ;;
  *)
    echo "Unknown network: $KLC_NETWORK"
    exit 1
esac

mkdir -p $KLC_DATADIR

exec kalycoind ${SELECT_NETWORK} \
  -rpcbind=0.0.0.0:3889 -rpcallowip=172.17.0.0/16 \
  -datadir=$KLC_DATADIR \
  -logevents \
  -rpcuser=$KLC_RPC_USER -rpcpassword=$KLC_RPC_PASS \
  -printtoconsole
